name: Basic Workflow

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Message
        run: echo "Hello, World!"
      - name: Say Hi
        run: echo "Hey Hi!"
